### ISSUE TITLE
VFNet-X's config file 404 error

### ISSUE THREAD

**Issue by likyoo** [hyz-xmaster/VarifocalNet#17]

**Comment by hyz-xmaster** [comment]
Hi you can get access to the config file via the link below:
https://github.com/hyz-xmaster/VarifocalNet/blob/master/configs/vfnet/vfnetx_r2_101_fpn_mdconv_c3-c5_mstrain_59e_coco.py

**Comment by likyoo** [comment]
Thanks a lot !!
