### ISSUE TITLE
About applying Varfifocal to yolox objectness loss

### ISSUE THREAD

**Issue by lucasjinreal** [hyz-xmaster/VarifocalNet#31]
Hi, I applied vaerifocal loss to yolox objectness (also tried cls loss), all make AP **massively** drop, this seems abnormal. Do u have any idea why?

It seems the objloss  decreased alittle bit, but cls loss get increased, (objloss: Varifocalloss, clsloss: BCELogits)

**Comment by hyz-xmaster** [comment]
Given your description, I think you may need to read our paper first to figure out what varifocal loss is and where to use it.

**Comment by lucasjinreal** [comment]
I have read your paper, I am not using objectness 0 or 1 as label, but iou based. I already give it up, useless in yolo like arch. I just wanna further investigate why.
