### ISSUE TITLE
About load model

### ISSUE THREAD

**Issue by yy18dlz** [hyz-xmaster/VarifocalNet#7]
Hi, when I load vfnet_r50_fpn_1x_coco_20201027-38db6f58.pth model
there has some error:
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please repor
t a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)

my torch version
>>> torch.__version__
'1.4.0+cu100'

**Comment by hyz-xmaster** [comment]
Hi, the published models are trained using PyTorch 1.6.0 and are not tested with PyTorch 1.4.0. The error information indicates that your version of PyTorch is not compatible with the file format you were reading. The possible solution is updating your PyTorch to a higher version, say, 1.6.0.

**Comment by yy18dlz** [comment]
> Hi, the published models are trained using PyTorch 1.6.0 and are not tested with PyTorch 1.4.0. The error information indicates that your version of PyTorch is not compatible with the file format you were reading. The possible solution is updating your PyTorch to a higher version, say, 1.6.0.

It works!
Thanks~
